### PR TITLE
Change driver initialization behavior:

### PR DESCRIPTION
**Pull request by davidsaada**
- Remove configuration file (base and size taken from driver).
    - Add initializtion variables (is initialized and rinit ref count).
    - Add destructor.

### CODE REVIEW

**Comment by geky** [comment]
Where did the configuration go?

I think we still need to provide the old constructor with an MBED_DEPRECATED message. Though I'm not sure what the behaviour should be.

**Comment by davidsaada** [comment]
@geky The only parameters in the config file were the base and size of the flash drive, both of which can be achieved from FlashIAP driver. Furthermore, it wasn't only after I removed the config file and read these from the driver that the block device test started working on K64F.
As for the constructor, I'm afraid it can't be done. Old constructor had default values in both parameters, making it ambiguous with the new default constructor. Any backward compatibility issues here? I don't think this worked anyway.

**Comment by geky** [comment]
Interesting, is there a config option for the FlashIAP driver?

> Any backward compatibility issues here? I don't think this worked anyway.

I'm concerned users called it with the arguments explicitly, even if it didn't work.

For example, storage-selector is going to break:
https://github.com/ARMmbed/storage-selector/blob/master/options/internal_flash.cpp#L21-L22

> I'm afraid it can't be done. Old constructor had default values in both parameters, making it ambiguous with the new default constructor.

We could provide an overloaded constructor without the default for the first argument. This would avoid the ambiguity.

If the old overload was broken, we may be able to get away with ignoring the arguments, but marking it as deprecated. This should warn users they need to change their code.

``` cpp
FlashIAPBlockDevice();

MBED_DEPRECATED("Don't do this")
FlashIAPBlockDevice(uint32_t address, uint32_t size = MBED_CONF_FLASHIAP_BLOCK_DEVICE_SIZE);
```

**Comment by davidsaada** [comment]
FlashIAP has no config options. Flash addresses are part of the board specific code.
Will add the deprecated constructor ignoring the two parameters

**Comment by geky** [comment]
> Flash addresses are part of the board specific code.

Don't the addresses used by the block device need to be configured somewhere? Or are you expecting users to use a SlicingBlockDevice if they need a specific section of flash?

**Comment by davidsaada** [comment]
That's exactly what I expect. I even started modifying the fs test here to do that (with a bunch of other changes such as using LittleFS instead of FAT), as it formats the entire flash, including the code...

**Comment by geky** [comment]
Ah ok, this makes sense now. But I'm not sure it's be best choice, since I think every time you use FlashIAP you will want to slice the storage? We should also run this by @marcuschangarm since he developed it initially and probably has the most use cases.

**Comment by davidsaada** [comment]
Slicing block device is the perfect solution for partitions, whether used with FkasIAP block device or SPIF or SD. You don't have to use it unless you want partitions. I agree that in the FladgIAP case you would want to use it more, as it hosts the code as well.
But that's beside the point. The physical flash parameters (base and size) are determined by the board support code and are exposed by the FladhIAP driver. If you only want a part of it, go ahead and use Slicing BD. That's the standard we developed

**Comment by geky** [comment]
I don't have that strong of an opinion, but we are breaking compatibility with this, and as far as I can tell FlashIAP is useless without slicing. I do get that the SlicingBlockDevice API has more powerful options, so that's a plus.

**Comment by davidsaada** [comment]
I probably didn't explain this clearly enough, but it's not a matter of compatibility like the fact that the previous method just didn't work. The FlashIAP BD is just a FlashIAP driver wrapper, and a such it just forwards the read/program/erase requests to the driver. Setting a base address different from the one known by the driver will simply be ignored by the driver (as it uses its own base for it).
Let's use an example: Say my internal flash starts at address A, but I want to use it starting address A + 0x1000., so I'll pass A + 0x1000 as an argument for the base parameter in the constructor. Still, when calling the read/program/erase APIs with an offset, FlashIAP driver will use the offset from A and not from A + 0x1000, which is not what I want of course.
This means that the only cases it could work so far would be the ones using the original base address (in storage selector for instance). So, right now, it will also work with the deprecated constructor (ignoring the base address). As the next step, we should change these places to use the new constructor (probably not many).

**Comment by davidsaada** [comment]
Anyway added the deprecation of the old constructor.

**Comment by davidsaada** [comment]
@dannybenor

**Comment by geky** [comment]
I'm not sure I understand, if you pass A + 0x1000 to the "base" parameter in the constructor, it looks like it gets added to the address in the read function. Am I missing something?
https://github.com/ARMmbed/flashiap-driver/blob/d1b5c5e995cdbb4003f7cb42ab1282d47a64ad86/FlashIAPBlockDevice.cpp#L115-L119


> So, right now, it will also work with the deprecated constructor (ignoring the base address). As the next step, we should change these places to use the new constructor (probably not many).

Sounds like a plan :+1: 

Though we should wait for @marcuschangarm's approval, since this is his repo. When do you need this in?

**Comment by davidsaada** [comment]
> Am I missing something?

You're not missing anything (it's me who needs to stop answering comments when I wake up). This will work of course.
Only problem here is the fact that the user should be aware of the base addresses of each device, if they want to make it work. This means that the config file should hold base addresses for ALL devices, which is redundant, as this information is already kept in the board support code. Alternatively, one can use FlashIAP itself in order to achieve the base address, which is a bit absurd to use with FlashIAP BD.
This is BTW the reason tests don't work on K64F. The config file only holds the value for the REALTEK_RTL8195AM board. Base address for K64F gets the default value of 0xFFFFFFFF, which makes the test crash.

**Comment by deepikabhavnani** [comment]
Slicing block device is better then configs for this case. My only concern would be Readme, we should be adding details of how to actually use this driver, as with current default constructor entire internal flash is available for read/writes.

**Comment by geky** [comment]
@deepikabhavnani also pointed out this repo is marked experimental, so it's less of a problem to break backwards compatibility. So we can remove the parameters, either now or later.

I'm on board :+1:

**Comment by marcuschangarm** [comment]
@MarceloSalazar

**Pull request merged**
